---
title: "Hair and Eye Colour Classifier Comparison"
output:
  pdf_document: default
  html_document: default
editor_options:
  markdown:
    wrap: 72
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r include=FALSE}
library(caret)
library(pROC) 
library(knitr)
library(tidyverse)
library(dplyr)
library(reshape2)

```

```{r include=FALSE}
df <- read.csv("PhenotypePredictions.tsv", sep="\t")

# Clean up formatting
df_clean <- df %>%
  mutate(Eye.Self.ID = recode(Eye.Self.ID,
                              "Intermediate - Green" = "Intermediate",
                              "Intermediate - Hazel" = "Intermediate",
                              "brown" = "Brown"))
df_clean <- df_clean %>%
  mutate(Hair.Predicted = recode(Hair.Predicted,
                              "black" = "Black"))

df_clean <- df_clean %>%
  mutate(Eye.Predicted = recode(Eye.Predicted,
                                 "brown" = "Brown"))

lapply(df_clean, unique) # Check if additional values need cleaning

# Add SNP data 
snp_df <- read.csv("snp_data.tsv", sep="\t")
snp_df$X <- sapply(snp_df$X, as.numeric)
combined_df <- left_join(df_clean, snp_df, by = c("Sample" = "X"))
combined_df_clean <- na.omit(combined_df)

SNP_cols = colnames(combined_df_clean[6:29])
for (col in SNP_cols) {
  combined_df_clean[[col]] <- factor(combined_df_clean[[col]], levels = unique(combined_df_clean[[col]]))
}

# Hair Colour Model
hair_levels <- union(unique(combined_df_clean$Hair.Predicted), unique(combined_df_clean$Hair.Self.ID))
combined_df_clean$Hair.Predicted <- factor(combined_df_clean$Hair.Predicted, levels = hair_levels)
combined_df_clean$Hair.Self.ID <- factor(combined_df_clean$Hair.Self.ID, levels = hair_levels)

# Train test split
set.seed(412)
train_index_hair <- createDataPartition(combined_df_clean$Hair.Self.ID, p=0.8, list=FALSE)
train_data_hair <- combined_df_clean[train_index_hair, ]
test_data_hair <- combined_df_clean[-train_index_hair, ]
fit_control_hair <- trainControl(method = "cv", number = 5, sampling = "up") # Upsampled due to low counts in minority class (blonde) 

# Remove SNPs with only one level
valid_SNP_cols_hair <- SNP_cols[sapply(train_data_hair[ , SNP_cols], function(x) length(unique(x)) > 1)]

SNP_str_hair = paste(valid_SNP_cols_hair, collapse = " + ")
model_formula_hair <- paste("Hair.Self.ID ~", SNP_str_hair)
model_hair <- train(as.formula(model_formula_hair), 
                    data = train_data_hair,
                    method = "rf",
                    trControl = fit_control_hair)
pred_hair <- predict(model_hair, newdata = test_data_hair)
prob_hair <- predict(model_hair, newdata = test_data_hair, type = "prob")

# Eye Colour Model
eye_levels <- union(unique(combined_df_clean$Eye.Predicted), unique(combined_df_clean$Eye.Self.ID))
combined_df_clean$Eye.Predicted <- factor(combined_df_clean$Eye.Predicted, levels = eye_levels)
combined_df_clean$Eye.Self.ID <- factor(combined_df_clean$Eye.Self.ID, levels = eye_levels)

# Train test split
set.seed(412)
train_index_eye <- createDataPartition(combined_df_clean$Eye.Self.ID, p=0.8, list=FALSE)

train_data_eye <- combined_df_clean[train_index_eye, ]

test_data_eye <- combined_df_clean[-train_index_eye, ]

fit_control_eye <- trainControl(method = "cv", number = 5, sampling = "up") # Upsampled due to low counts in minority class (intermediate) 

# Remove SNPs with only one level
valid_SNP_cols_eye <- SNP_cols[sapply(train_data_eye[ , SNP_cols], function(x) length(unique(na.omit(x))) > 1)]


SNP_str_eye = paste(valid_SNP_cols_eye, collapse = " + ")
model_formula_eye <- paste("Eye.Self.ID ~", SNP_str_eye)
model_eye <- train(as.formula(model_formula_eye), 
                    data = train_data_eye,
                    method = "rf",
                    trControl = fit_control_eye)
pred_eye <- predict(model_eye, newdata = test_data_eye)
prob_eye <- predict(model_eye, newdata = test_data_eye, type = "prob")

conf_matrix_hair <- confusionMatrix(pred_hair,test_data_hair$Hair.Self.ID)
conf_matrix_eye <- confusionMatrix(pred_eye, test_data_eye$Eye.Self.ID)

conf_matrix_eye_Illumina <- confusionMatrix(combined_df_clean$Eye.Predicted, combined_df_clean$Eye.Self.ID)
conf_matrix_hair_Illumina <- confusionMatrix(combined_df_clean$Hair.Predicted, combined_df_clean$Hair.Self.ID)
```

```{r}
kable(conf_matrix_hair$table, caption = "Hair Colour - ML Model")
```

```{r}
kable(conf_matrix_eye$table, caption = "Eye Colour - ML Model")
```

```{r}
kable(conf_matrix_hair_Illumina$table, caption = "Hair Colour - Illumina Predictions")
```

```{r}
kable(conf_matrix_eye_Illumina$table, caption = "Eye Colour - Illumina Predictions")
```

```{r include=FALSE}
# One-hot encode true labels

true_labels_eye <- test_data_eye$Eye.Self.ID 
actual_mat_eye <- model.matrix(~ true_labels_eye - 1) 
colnames(actual_mat_eye) <- levels(true_labels_eye)

# ROC plots

par(mfrow=c(1, length(levels(true_labels_eye)))) 
roc_list_eye <- list()
auc_list_eye <- c()
```

```{r}
for (class in levels(true_labels_eye)) {
  roc_obj <- roc(actual_mat_eye[, class], prob_eye[, class]) 
  auc_val <- auc(roc_obj) 
  plot(roc_obj, main = paste("Eye -", class, "\nAUC:",round(auc_val, 3)), col = "blue", lwd = 2) 
  roc_list_eye[[class]] <- roc_obj 
  auc_list_eye[class] <- auc_val 
}

kable(as.data.frame(auc_list_eye),
  col.names = c("AUC"), caption = "Eye Colour - AUC per Class")
```

```{r include=FALSE}
true_labels_hair <- test_data_hair$Hair.Self.ID 
actual_mat_hair <- model.matrix(~ true_labels_hair - 1) 
colnames(actual_mat_hair) <- levels(true_labels_hair)

# ROC plots

par(mfrow=c(1, length(levels(true_labels_hair)))) 
roc_list_hair <-list() 
auc_list_hair <- c()
```

```{r}
for (class in levels(true_labels_hair)) {
  roc_obj <- roc(actual_mat_hair[, class], prob_hair[, class]) 
  auc_val <- auc(roc_obj) 
  plot(roc_obj, main = paste("Hair -", class, "\nAUC:",round(auc_val, 3)), col = "blue", lwd = 2) 
  roc_list_hair[[class]] <- roc_obj 
  auc_list_hair[class] <- auc_val 
}
```

```{r}
kable(as.data.frame(auc_list_hair), col.names = c("AUC"), caption ="Hair Colour - AUC per Class")
```
